config.ini.example, nmcli_dmenu
Using rofi the passwords are typed in clear text. I found it partially
annoying and decided to add an option to use pinentry.
:shipit:
=> Added support for pinentry

config.ini.example, nmcli_dmenu
Some people (myself) have more than a few dozen VPN connections available, as well as many seen network options. With so many options available, the default and unconfiguable number of lines makes dmenu stretch well beyond the size of the screen. This pull-request allows the user to configure an option in the config file, "lines", which changes the default "num_lines" variable if the configuration exists.
=> Add config option for number of lines to display

nmcli_dmenu
It seems that rofi doesn't accept "" character, but accecp " " character, thus after "" other options not showing. Replaceing "" with " " can fix this problem.
Before edition:
[https://s23.postimg.org/582fs3ajf/before.png](https://s23.postimg.org/582fs3ajf/before.png)
After edition:
[https://s29.postimg.org/qozs7lcmf/after.png](https://s29.postimg.org/qozs7lcmf/after.png)
dmenu still works:
[https://s24.postimg.org/kdd0zivqt/after_dmenu.png](https://s24.postimg.org/kdd0zivqt/after_dmenu.png)
=> fix rofi not showing other options(Disable wifi, etc), dmenu still works

networkmanager_dmenu
The correct line number should be len(conn_acts), but not len(conn_names), which is the lenght of the encoded str.
=> fix a minor bug in the new feature "delete existing conns"

networkmanager_dmenu
Apparently NM uses a temporary hardware address, when not connected to a access point.
I recognised this, because the MAC address was different than the one set in the connection. Running `ip addr show` once when connected to a AP and once when not connected at all showed, that two different MAC addresses were reported. `get_permanent_hw_address` always returns the correct one.
Fixes #36
=> Use the permanent hardware address

networkmanager_dmenu
The following traceback intermittently shows up, which this change fixes:
```
➔  dex /usr/share/applications/networkmanager_dmenu.desktop
Traceback (most recent call last):
File "/usr/bin/networkmanager_dmenu", line 612, in <module>
run()
File "/usr/bin/networkmanager_dmenu", line 603, in run
gsm_actions = create_gsm_actions(gsms, active)
File "/usr/bin/networkmanager_dmenu", line 288, in create_gsm_actions
i.get_connection().is_type(NM.SETTING_GSM_SETTING_NAME)]
AttributeError: 'NoneType' object has no attribute 'is_type'
```
=> Fix AttributeError in create_gsm_actions()

networkmanager_dmenu
Boy, that NM API is not easy to find. I think this is pretty effective though.
The nm-applet also shows Ethernet connections, if you have a computer with Ethernet. I use this a lot for applying different DHCP options or even static IPs to some networks that I frequently use. Allowing me to connect or disconnect them with dmenu is going to save a lot of time. Maybe there are more people like me? I hope you don't mind me putting the Ethernet at the top. I did that because that's what nm-applet did.
On my machine (ubuntu 16.04), the Ethernet, VPN and WiFi stuff all shows up in a similar list to when I use nm-applet. Disabling and Enabling other Ethernet Connections were all tested and worked.
=> Also control Ethernet and static IP connections.

networkmanager_dmenu
WIFI connections created by networkmanager-dmenu don't have their MAC address set. This can lead to problems such as #58, where the connection is not determined valid for that adapter by `filter_connections`.
Note: This change was necessary on my Arch Linux system using NetworkManager 1.18.0.
=> Add MAC when creating wifi profiles.

networkmanager_dmenu
This adds a `single_line` option, suitable for running dmenu without multiple lines or rofi with a dmenu-emulating theme. With this option, padding (which is mostly useful for visual alignment across multiple lines) is removed, and the `empty_action` is omitted.
Example `config.ini`:
```
[dmenu]
dmenu_command = rofi -theme dmenu
rofi_highlight = True
single_line=True
[editor]
gui_if_available = True
```
Example rofi theme: [dmenu.rasi](https://github.com/davatorium/rofi/blob/next/themes/dmenu.rasi)
=> Add single_line option

networkmanager_dmenu
I have many connection profiles, and sometimes I just want to quickly locate the active connection (for example, to disconnect from VPN).
Right now, active connections are marked with `**`. Instead of remembering the connection name, I'd like to just type this prefix in the filter box. However, `**` symbol is _also_ used for connection quality, so by typing `**` I don't filter anything and I still have a lot of connections visible.
With this PR I change the active connections marker to `==`, which is unique, and so now it's easy to jump directly to the active connection, by typing `==` in the filter box.
=> Use different icon for active connections

networkmanager_dmenu
networkmanager-dmenu fails to start as the dmenu_command is belling called with the "-wifi_chars" argument. It needs to be removed from the list of arguments passed over to dmenu_command. Fixes #79.
=> Remove wifi_chars from dmenu_command args

networkmanager_dmenu
First try to open gnome-control-center's network panel before the nm-connection-editor. If gnome-control-center is not installed it will not be used, and will fall back to nm-connection-editor.
=> Added gnome-control-center support for 'Launch Connection Manager'

README.rst, networkmanager_dmenu
With this PR, saved connections can be accessed with `list_saved = False`, without polluting the main menu:
=> Add a separate sub-menu for saved connections

networkmanager_dmenu
Follow-up to #88
Like you said in https://github.com/firecat53/networkmanager-dmenu/pull/88#issuecomment-691177690 using `functools` isn't needed here - I didn't look closely at the `Action` class and didn't notice it already has a way to pass arguments to the underlying function.
To expand on what `functools.partial` does: It essentially "binds" the given arguments to the given function, returning a new function which can then be called without arguments. The concept is usually known as [currying](https://en.wikipedia.org/wiki/Currying) or "partial application". Since we already have a much simpler way to pass arguments, it's indeed not needed at all here.
=> Avoid unneeded functools

networkmanager_dmenu
I use NetworkManager for Bluetooth tethering with Android - for some reason, NetworkManager itself doesn't provide any way to disable/enable Bluetooth radios, even though it can connect to them just fine, if they are enabled.
Thus, I always need to first use rfkill or blueman to enable Bluetooth before I can connect with networkmanager_dmenu. With this change, I can do it all right from rofi.
---
Admittedly, this is a bit of a hack. I first thought I'd use the commandline output of the `rfkill` tool first, but its output seems to have changed a bit between different `util-linux` versions. It does offer JSON output since utils-linux v2.31.1 (December 2017) which does seem to be part of Debian Buster (the current stable) and Ubuntu 18.04 LTS, but not e.g. Ubuntu 16.04 LTS which is still …
=> Add toggle for Bluetooth

networkmanager_dmenu
Filter connections by mac-address, interface-name or neither, depending
on what's set in the profile.
Fixes #91, but does *not* help with #92 for some reason.
=> Improve connection/adapter filtering

networkmanager_dmenu
Hi, I noticed that since I added another patch to my dmenu which changes the `dmenu -h` output the check for password patch was broken; I think checking for a uppercase `P` is enough, since the help output is all in lowecase otherwise.
For reference, this is my `dmenu -h`:
``` sh
usage: dmenu [-bfirPv] [-l lines] [-p prompt] [-fn font] [-m monitor]
[-h height]
[-nb color] [-nf color] [-sb color] [-sf color]
[-nhb color] [-nhf color] [-shb color] [-shf color] [-w windowid]
```
=> Fix dmenu password patch check

networkmanager_dmenu
I noticed that the passphrase input had stopped working while using bemenu. The issue occurs when dmenu_cmd is run to prompt for the passphrase - nothing is provided on the subprocess stdin. Bemenu will hang indefinitely waiting for input.
This patch simply sends an empty string on stdin to the dmenu command during the passphrase prompt.
=> Provide empty input to passphrase dmenu command

networkmanager_dmenu
Hello,
If the script is run with the option -O and -OO, asserts will be removed and the user will not have an information more clear about why it crashed.
This patch doesn't make the script 100% safe to run with python optimization options but it's a good start.
=> Avoid usage of asserts

README.md, config.ini.example, networkmanager_dmenu
This PR allows the user to set the format of the dmenu entry as well as the description and prompt of the pin entry via the config. That should close #62. The dmenu format has placeholders for the name, the security type, and three different ways of showing signal strength: percentage, bars (current default), and icon. For example, the setting
```
format = {name} ({sec}) {signal}%% {icon}
```
produces the following output (with the appropriate setting of `wifi_icons`):
(yes, I'm at the airport right now...)
=> Make dmenu and pinentry formats configurable

README.md, config.ini.example, networkmanager_dmenu
I added 2 features.
1. customizable active prefix
```ini
[dmenu]
active_chars = v  # (default: ==)
```
2. highlight active connection and customizable style for wofi
I don't use other menus, and don't know whether it's possible there, so I only support wofi.
> **Warning**
> There's a breaking change. I renamed `rofi_highlight` to `highlight`.
> In my opinion, it's better than introducing another `wofi_highlight` field.
```ini
[dmenu]
highlight = True
```
> Default highlighting style is bold text.
The followings are fields for the highlighting style.
```ini
[dmenu]
highlight_fg = #f2b468
highlight_bg = black
highlight_bold = False
```
Please tell me what to do if I missed something. Thank you!
=> feat: customizable active prefix & highlighting style for wofi

networkmanager_dmenu
This adds an extra check before calling `bluetoothctl`, making sure that `bluetoothd` is running so the command doesn't hang.
Maybe there are better ways to perform this check, so let me know if the code could be improved (actually, this is my first pull request ever, so let me know if I'm doing something wrong).
Fixes #131
=> Check if bluetoothd is running before executing bluetoothctl

README.md, config.ini.example, networkmanager_dmenu
If gnome is installed, but you are not in a gnome environment, gnome-control-center is still used. However, it will not work outside of gnome shells.
This PR adds the ability to select which GUI editor to use, the fallback value is still gnome-control-center.
However, this will break for people who do not have gnome installed as it will not fall through to nm-connection-editor.
Configuration example is as follows,
```
[editor]
gui = nm-connection-editor
```
=> add ability to select gui

README.md, config.ini.example, networkmanager_dmenu
Small change to launch connection editor function.
Allow for adding extra arguments to the terminal in the config. e.g.
`[editor]
terminal = foot --app-id floating`
=> Allow for terminal arguments

networkmanager_dmenu
Pad strength bars with spaces to the left.
=> Add padding to strength bars

networkmanager_dmenu.desktop
Noticed it because there was a space between the title and the description in the dmenu entry.
I don't know how you manage the branches, feel free to edit the PR to merge into the correct one.
=> Remove a space after the title in the .desktop

networkmanager_dmenu
`dmenu_pass` function rejects all command exept `dmenu`. But it is called for `wmenu` in line 396, which makes `pass_prompts` `None`.
This is the error message:
```
Traceback (most recent call last):
File "/home/hang/projects/networkmanager-dmenu/./networkmanager_dmenu", line 1485, in <module>
main()
~~~~^^
File "/home/hang/projects/networkmanager-dmenu/./networkmanager_dmenu", line 1481, in main
run()
~~~^^
File "/home/hang/projects/networkmanager-dmenu/./networkmanager_dmenu", line 1472, in run
sel()
~~~^^
File "/home/hang/projects/networkmanager-dmenu/./networkmanager_dmenu", line 598, in __call__
self.func(*self.args)
~~~~~~~~~^^^^^^^^^^^^
File "/home/hang/projects/networkmanager-dmenu/./networkmanager_dmenu", line 652, in process_ap
password = get_passphrase()
File …
```
=> fix: correct password options for wmenu
